#pragma once

typedef enum BfTreeTraversals {
  BF_TREE_TRAVERSAL_UNKNOWN,
  BF_TREE_TRAVERSAL_LR_LEVEL_ORDER,
  BF_TREE_TRAVERSAL_LR_REVERSE_LEVEL_ORDER,
  BF_TREE_TRAVERSAL_POST_ORDER
} BfTreeTraversal;
